=== jettero/grm/MapGen.dtd
<!ELEMENT MapGen (option*, tile_group*, map)>
<!ELEMENT option EMPTY>
<!ELEMENT tile_group EMPTY>
<!ELEMENT closure EMPTY>
<!ELEMENT map (row*)>
<!ELEMENT row (tile*)>
<!ELEMENT tile (closure*)>

<!ATTLIST row ypos CDATA #REQUIRED>
<!ATTLIST tile xpos CDATA #REQUIRED>
<!ATTLIST tile type CDATA #REQUIRED>
<!ATTLIST tile_group name CDATA #REQUIRED>
<!ATTLIST tile_group type CDATA #REQUIRED>
<!ATTLIST tile_group loc CDATA #REQUIRED>
<!ATTLIST tile_group size CDATA #REQUIRED>

<!ATTLIST option name   CDATA #REQUIRED>
<!ATTLIST option value  CDATA #REQUIRED>

<!ATTLIST closure dir            (north|east|south|west)   #REQUIRED>
<!ATTLIST closure type           (room|corridor|wall|door) #REQUIRED>
<!ATTLIST closure open           (yes|no) #IMPLIED>
<!ATTLIST closure locked         (yes|no) #IMPLIED>
<!ATTLIST closure stuck          (yes|no) #IMPLIED>
<!ATTLIST closure secret         (yes|no) #IMPLIED>
<!ATTLIST closure major_open_dir (north|east|south|west) #IMPLIED>
<!ATTLIST closure minor_open_dir (north|east|south|west) #IMPLIED>

=== jettero/grm/vis1.map.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE MapGen SYSTEM "MapGen.dtd">
<?xml-stylesheet type="text/xsl" href="MapGen.xsl"?>


<MapGen>
  <option name="bounding_box" value="40x40" />
  <option name="cell_size" value="23x23" />
  <option name="exporter" value="Games::RolePlay::MapGen::Exporter::XML" />
  <option name="fname" value="vis1.map.xml" />
  <option name="generator" value="Games::RolePlay::MapGen::Generator::Basic" />
  <option name="max_room_size" value="7x7" />
  <option name="max_span" value="50" />
  <option name="min_room_size" value="2x2" />
  <option name="num_rooms" value="2d4" />
  <option name="remove_deadend_percent" value="60" />
  <option name="same_node_percent" value="30" />
  <option name="same_way_percent" value="90" />
  <option name="sparseness" value="10" />
  <option name="tile_size" value="5" />
  <option name="x_size" value="20" />
  <option name="xml_input_file" value="vis1.map.xml" />
  <option name="y_size" value="20" />
  <option name="closed_corridor_corridor_door_percent" value="door: 1; locked: 30; secret: 95; stuck: 10;" />
  <option name="closed_room_corridor_door_percent" value="door: 5; locked: 30; secret: 95; stuck: 10;" />
  <option name="open_corridor_corridor_door_percent" value="door: 1; locked: 50; secret: 10; stuck: 25;" />
  <option name="open_room_corridor_door_percent" value="door: 95; locked: 50; secret: 2; stuck: 25;" />
  <tile_group name="Room #1" type="room">
    <rectangle loc="32,22" size="6x14" />
  </tile_group>
  <tile_group name="Room #2" type="room">
    <rectangle loc="0,0" size="14x8" />
  </tile_group>
  <tile_group name="Room #3" type="room">
    <rectangle loc="0,24" size="10x14" />
  </tile_group>
  <tile_group name="Room #4" type="room">
    <rectangle loc="14,24" size="12x14" />
  </tile_group>
  <tile_group name="Room #5" type="room">
    <rectangle loc="28,12" size="10x6" />
  </tile_group>
  <tile_group name="Room #6" type="room">
    <rectangle loc="22,0" size="12x4" />
  </tile_group>
  <tile_group name="Room #7" type="room">
    <rectangle loc="2,8" size="10x12" />
  </tile_group>
  <map>
    <row ypos="0">
      <tile xpos="0" type="room">
        <closure dir="north" type="wall" />
        <closure dir="west" type="wall" />
      </tile>
      <tile xpos="1" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="2" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="3" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="4" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="5" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="6" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="7" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="8" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="9" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="10" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="11" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="12" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="13" type="room">
        <closure dir="north" type="wall" />
        <closure dir="east" type="wall" />
      </tile>
      <tile xpos="14" type="wall" />
      <tile xpos="15" type="wall" />
      <tile xpos="16" type="wall" />
      <tile xpos="17" type="wall" />
      <tile xpos="18" type="wall" />
      <tile xpos="19" type="wall" />
      <tile xpos="20" type="wall" />
      <tile xpos="21" type="wall" />
      <tile xpos="22" type="room">
        <closure dir="north" type="wall" />
        <closure dir="west" type="wall" />
      </tile>
      <tile xpos="23" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="24" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="25" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="26" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="27" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="28" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="29" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="30" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="31" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="32" type="room">
        <closure dir="north" type="wall" />
      </tile>
      <tile xpos="33" type="room">
        <closure dir="north" type="wall" />
        <closure dir="east" type="wall" />
      </tile>
      <tile xpos="34" type="wall" />
      <tile xpos="35" type="wall" />
      <tile xpos="36" type="wall" />
      <tile xpos="37" type="wall" />
      <tile xpos="38" type="wall" />
      <tile xpos="39" type="wall" />
    </row>
    <row ypos="1">
      <tile xpos="0" type="room">
        <closure dir="west" type="wall" />
      </tile>
      <tile xpos="1" type="room" />
      <tile xpos="2" type="room" />
      <tile xpos="3" type="room" />
      <tile xpos="4" type="room" />
      <tile xpos="5" type="room" />
      <tile xpos="6" type="room" />
      <tile xpos="7" type="room" />
      <tile xpos="8" type="room" />
      <tile xpos="9" type="room" />
      <tile xpos="10" type="room" />
      <tile xpos="11" type="room" />
      <tile xpos="12" type="room" />
      <tile xpos="13" type="room">
        <closure dir="east" type="wall" />
      </tile>
      <tile xpos="14" type="wall" />
      <tile xpos="15" type="wall" />
      <tile xpos="16" type="wall" />
      <tile xpos="17" type="wall" />
      <tile xpos="18" type="wall" />
      <tile xpos="19" type="wall" />
      <tile xpos="20" type="wall" />
      <tile xpos="21" type="wall" />
      <tile xpos="22" type="room">
        <closure dir="west" type="wall" />
      </tile>
      <tile xpos="23" type="room" />
      <tile xpos="24" type="room" />
      <tile xpos="25" type="room" />
      <tile xpos="26" type="room" />
      <tile xpos="27" type="room" />
      <tile xpos="28" type="room" />
      <tile xpos="29" type="room" />
      <tile xpos="30" type="room" />
      <tile xpos="31" type="room" />
      <tile xpos="32" type="room" />
      <tile xpos="33" type="room">
        <closure dir="east" type="wall" />
      </tile>
      <tile xpos="34" type="wall" />
      <tile xpos="35" type="wall" />
      <tile xpos="36" type="wall" />
      <tile xpos="37" type="wall" />
      <tile xpos="38" type="wall" />
      <tile xpos="39" type="wall" />
    </row>
    <row ypos="2">
      <tile xpos="0" type="room">
        <closure dir="west" type="wall" />
      </tile>
      <tile xpos="1" type="room" />
      <tile xpos="2" type="room" />
      <tile xpos="3" type="room" />
      <tile xpos="4" type="room" />
      <tile xpos="5" type="room" />
      <tile xpos="6" type="room" />
      <tile xpos="7" type="room" />
      <tile xpos="8" type="room" />
      <tile xpos="9" type="room" />
      <tile xpos="10" type="room" />
      <tile xpos="11" type="room" />
      <tile xpos="12" type="room" />
      <tile xpos="13" type="room">
        <closure dir="east" type="wall" />
      </tile>
      <tile xpos="14" type="wall" />
      <tile xpos="15" type="wall" />
      <tile xpos="16" type="wall" />
      <tile xpos="17" type="wall" />
      <tile xpos="18" type="wall" />
      <tile xpos="19" type="wall" />
      <tile xpos="20" type="wall" />
      <tile xpos="21" type="wall" />
      <tile xpos="22" type="room">
        <closure dir="west" type="wall" />
      </tile>
      <tile xpos="23" type="room" />
      <tile xpos="24" type="room" />
      <tile xpos="25" type="room" />
      <tile xpos="26" type="room" />
      <tile xpos="27" type="room" />
      <tile xpos="28" type="room" />
      <tile xpos="29" type="room" />
      <tile xpos="30" type="room" />
      <tile xpos="31" type="room" />
      <tile xpos="32" type="room" />
      <tile xpos="33" type="room">
        <closure dir="east" type="door" locked="yes" stuck="no" secret="no" open="no" major_open_dir="east" minor_open_dir="south" />
      </tile>
      <tile xpos="34" type="corridor">
        <closure dir="north" type="wall" />
        <closure dir="west" type="door" locked="yes" stuck="no" secret="no" open="no" major_open_dir="east" minor_open_dir="south" />
      </tile>
      <tile xpos="35" type="corridor">
        <closure dir="north" type="wall" />
        <closure dir="east" type="wall" />
      </tile>
      <tile xpos="36" type="wall" />
      <tile xpos="37" type="wall" />
      <tile xpos="38" type="wall" />
      <tile xpos="39" type="wall" />
    </row>
    <row ypos="3">
      <tile xpos="0" type="room">
        <closure dir="west" type="wall" />
      </tile>
      <tile xpos="1" type="room" />
      <tile xpos="2" type="room" />
      <tile xpos="3" type="room" />
      <tile xpos="4" type="room" />
      <tile xpos="5" type="room" />
      <tile xpos="6" type="room" />
      <tile xpos="7" type="room" />
      <tile xpos="8" type="room" />
      <tile xpos="9" type="room" />
      <tile xpos="10" type="room" />
      <tile xpos="11" type="room" />
      <tile xpos="12" type="room" />
      <tile xpos="13" type="room">
        <closure dir="east" type="wall" />
      </tile>
      <tile xpos="14" type="wall" />
      <tile xpos="15" type="wall" />
      <tile xpos="16" type="wall" />
      <tile xpos="17" type="wall" />
      <tile xpos="18" type="wall" />
      <tile xpos="19" type="wall" />
      <tile xpos="20" type="wall" />
